# SECURE
services:
  fastapi-app:
    build: ./app
    expose:
      - 8000
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  nginx:
    image: nginx:latest
    ports:
      # - "80:80"
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi-app

#  run this 
  # docker compose up --scale fastapi-app=3 -d

# INSECURE

# version: '3.8'

# services:
#   app:
#     build: ./app
#     container_name: fastapi-app
#     expose:
#       - "8000"
#     restart: always

#   nginx:
#     image: nginx:latest
#     container_name: nginx-proxy
#     ports:
#       - "81:80"
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#     depends_on:
#       - app
#     restart: always
