version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INSTANCE_NAME=App1
    ports:
      - "3001:3000"

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INSTANCE_NAME=App2
    ports:
      - "3002:3000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
